### ISSUE TITLE
openstask

### ISSUE THREAD

**Issue by ksh0165** [ksh0165/Spring-4-MVC#29]
# kvm 관련 문제 해결 하는 중

source /root/keystonerc_admin

###참고 URL:

**Comment by ksh0165** [comment]
lsmod | grep kvm

**Comment by ksh0165** [comment]
# 에러문구 : virnetsocketreadwire end of file while reading data input/output error

# Libvirt 버전 virsh --version

# 재시작 : systemctl restart libvirtd

**Comment by ksh0165** [comment]
# 코어 수 : ll -d /sys/devices/system/cpu/cpu? | wc -l

**Comment by ksh0165** [comment]
서버 리스트 확인

 openstack compute service list

**Comment by ksh0165** [comment]
# NoValidHost: No valid host was found. There are not enough hosts available

/var/log/nova/nova-conductor.log file, there is the log:

2017-08-05 00:22:29.046 3834 WARNING nova.scheduler.utils [req-89c159c7-b40a-43eb-8f0d-9306eb73e83a 2a5fa182fb1b459980db09cd1572850e 0d5998f2f7ec4c4892a32e06bafb19df - - -] Failed to compute_task_build_instances: No valid host was found. There are not enough hosts available.
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 199, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 104, in select_destinations
    dests = self.driver.select_destinations(ctxt, spec_obj)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 74, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.

2017-08-05 00:22:29.048 3834 WARNING nova.scheduler.utils [req-89c159c7-b40a-43eb-8f0d-9306eb73e83a 2a5fa182fb1b459980db09cd1572850e 0d5998f2f7ec4c4892a32e06bafb19df - - -] [instance: 2011e343-c8fc-4ed0-8148-b0d2b5ba37c3] Setting instance to ERROR state.
2017-08-05 00:22:30.785 3834 WARNING oslo_config.cfg [req-89c159c7-b40a-43eb-8f0d-9306eb73e83a 2a5fa182fb1b459980db09cd1572850e 0d5998f2f7ec4c4892a32e06bafb19df - - -] Option "auth_plugin" from group "neutron" is deprecated. Use option "auth_type" from group "neutron".

**Comment by ksh0165** [comment]
# openstack 이미지

openstack image list

**Comment by ksh0165** [comment]
nova list

# 오픈 소스 : http://dev.crois.net/2017/11/30/openstack-kvm%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-openstack-pike-%EC%84%A4%EC%B9%98-v-0-1-2017-11-30/

**Comment by ksh0165** [comment]
systemctl status openstack-nova-api

openstack compute service list --service nova-compute

systemctl status openstack-nova-compute

openstack compute service list

openstack hypervisor list

# 호스트 찾기 :  su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
